### PR TITLE
Paramter hour becomes optional

### PR DESCRIPTION
**Pull request by inelgnu**
avoid typing date every time

### CODE REVIEW

**Comment by gnugat** [comment]
Would you mind changing the argument into an option? Optional arguments don't make any sens to me :) .

Anyway this PR cannot be merged for now: currently only quarter hours are supported (`h:00`, `h:15`, `h:30` and `h:45`) which means that with your change, TempoSimple can crash when punching at times like `09:44` or `18:23`.
I know it sucks but it was a shortcut I took to ship the project as quickly as possible. Currently work is done to use [DDD Time](https://github.com/ddd-php/Time) to handle time computations. When this is done, any minutes will be accepted and your PR will be merged.

Please, have a long cup of tea meanwhile :) .

**Comment by inelgnu** [comment]
it sucks ! :-) bisou

**Comment by inelgnu** [comment]
InputArgument::OPTIONAL The argument is optional and therefore can be omitted

http://symfony.com/doc/current/components/console/introduction.html#using-command-arguments

**Comment by gnugat** [comment]
I know optional arguments exist, I just prefer to use options instead :) .

**Comment by inelgnu** [comment]
ping @gnugat

**Comment by gnugat** [comment]
I can't check if it doesn't break anything, so I'll just trust you on this one :) .

:shipit: :shipit: :shipit: !

**Pull request merged**
