### PR TITLE
Installation is broken

### PR DESCRIPTION
**Pull request by gnugat**
To install TempoSimple, you simply need to get the source and download the dependencies:

```
git clone https://github.com/gnugat/tempo-simple.git
cd tempo-simple
git checkout -t origin/fix/install
composer install
```

You need then to create the database:

```
php app/console doctrine:database:create
php app/console schema
```

Problem is: when launching the console, the following error occurs:

```
[PDOException]                                     
SQLSTATE[42000] [1049] Unknown database 'xxx'
```

This means that currently the user has to manually create the database and schema :/ .

### CODE REVIEW

**Comment by tucksaun** [comment]
If you use  `php app/console doctrine:database:create -vvv` or  `php app/console  -vvv` you will see your problem :)

Basically in your `PunchTimeCardCommand::configure` you execute timeCardRepository->findLastOne().
But you need to remember that `configure` is triggered on **all** commands when you launch php app/console so you should not perform this kind of tasks in this method.

For you $startHour it would be better to do the $this->timeCardRepository->findLastOne() in your the execute() method.

Oh and BTW, when cloning a repo you can switch to a specific branch in one command:

```
git clone https://github.com/gnugat/tempo-simple.git -b fix/install
```

**Comment by gnugat** [comment]
Thank you @tucksaun! I guess that's one of the drawbacks of using services in `configure`, I'll add it in the [Symfony's documentation](https://github.com/symfony/symfony-docs/pull/3621).

The thing is, if I remove it from the `configure` method, users won't be able to know the default values. Another solution might be to create a separate application for installation purpose.

**Comment by tucksaun** [comment]
Think about it otherwise, you will make this request on **every** instanciation of your Application, so each time you trigger the app/console.... It's like issuing a doctrine query in the constructor of a twig extensions. IMO it's a bad habit.

If you **really** want that, you can try catch the findLastOne to handle the case where no database is present.
It could solve another problem: Imagine your user rename database, he needs to clear the cache, but the command try to connect to the database and fails so you can't clear the cache (at least not in a clean way). This is just an example I think we can't find other uses cases like that ;)

**Comment by gnugat** [comment]
Well I've always thought that loading commands in the web environment was a bit unnecessary.
I'll use your fix: in my case there's no web interface for now, so I should be fine (and it's the most pragmatic solution so far).

**Comment by tucksaun** [comment]
When speaking about Application I'm referring to `FrameworkBundle\Console\Application` don't worry for the web POV ;)

**Comment by gnugat** [comment]
Ok I thought you were saying that commands were created in each web request.

Well IMHO there's no real time concerns in the console. Futhermore, I'm sure doctrine is good enough to cache the requests, and if it's not the case I could make the calls lazy.

Thank you very much for your anwsers, I've learned a lot today thanks to you :) .

**Pull request merged**
